version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_install:
      # Install the project with documentation dependencies using pip
      # This is the standard approach for PEP 517/518 compliant projects
      - pip install ".[docs,xarray]"

sphinx:
  configuration: docs/source/conf.py
