services:
  lint:
    image: space-packets-linting:latest
    build:
      target: lint

  style:
    image: space-packets-style:latest
    build:
      target: style

  3.8-tests:
    image: space-packets-3.8-test:latest
    build:
      target: test
      args:
        - BASE_IMAGE_PYTHON_VERSION=3.8

  3.9-tests:
    image: space-packets-3.9-test:latest
    build:
      target: test
      args:
        - BASE_IMAGE_PYTHON_VERSION=3.9

  3.10-tests:
    image: space-packets-3.10-test:latest
    build:
      target: test
      args:
        - BASE_IMAGE_PYTHON_VERSION=3.10

  3.11-tests:
    image: space-packets-3.11-test:latest
    build:
      target: test
      args:
        - BASE_IMAGE_PYTHON_VERSION=3.11

  3.12-tests:
    image: space-packets-3.12-test:latest
    build:
      target: test
      args:
        - BASE_IMAGE_PYTHON_VERSION=3.12

  3.11-tests-min-deps:
    image: space-packets-3.11-test:latest
    build:
      target: test
      args:
        - BASE_IMAGE_PYTHON_VERSION=3.11
