name: Test with Matrix of Python Versions
on: pull_request
jobs:
  python-version-matrix:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    uses: ./.github/workflows/test-python-version.yml
    with:
      python-version: ${{ matrix.python-version }}