name: Test on Specific Python Version
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
jobs:
  test:
    name: Run Tests in Docker
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Build test Docker image
      run: docker build . --file Dockerfile --target test --build-arg BASE_IMAGE_PYTHON_VERSION=${{ inputs.python-version }} --tag space-packet-parser-${{ inputs.python-version }}-test:latest
    - name: Run Tests in Docker
      run: docker run -i space-packet-parser-${{ inputs.python-version }}-test:latest